-- Migration: 0024_events_nostr_model
-- Status:    NO-OP (superseded by 0025_events_nostr_model_v2)
-- Purpose: Retained as a no-op to preserve migration ordering. The event-model
--          swap this file used to carry now lives in 0025_events_nostr_model_v2.
-- Ticket: N/A
--
-- Originally this migration performed the event-model swap merged from the
-- panamia-resilience fork (commit 4d89e0b7). It never applied anywhere: on the
-- first deploy it aborted with
--
--   42710  constraint "events_host_profile_id_profiles_id_fk" for relation
--          "events" already exists
--
-- Section 6 re-added the host/venue FKs under names that 0017 had already
-- created (0017 lines 108-111), so the whole migration rolled back. It also
-- carried a latent conflict: 0017's host FK is ON DELETE SET NULL, which
-- contradicts the SET NOT NULL this migration puts on the same column --
-- deleting a profile would raise a not-null violation rather than the intended
-- RESTRICT.
--
-- The corrected migration is 0025_events_nostr_model_v2, which drops the
-- pre-existing host/venue FKs (both 0004's pair and 0017's pair) before
-- re-adding a single clean pair. This file is retained as a no-op to preserve
-- migration ordering, per the precedent set by 0005.
--
-- Reversible: N/A (no-op)

SELECT 1;
