-- =============================================================================
-- MIGRATION TEMPLATE
-- =============================================================================
-- Drizzle Kit generates migration files automatically via 'npx drizzle-kit generate'.
-- After generation, open the new file and add the required documentation headers
-- at the top (before the generated SQL). This file is NOT processed by Drizzle.
--
-- Naming convention: NNNN_snake_case_description.sql (Drizzle assigns the number)
-- Example: 0001_add_pet_sitting_tables.sql
-- =============================================================================

-- Migration: <name_matching_file>
-- Purpose: <Brief description of WHY this migration exists - business context>
-- Ticket: PANA-XXX (or N/A for infrastructure changes)
-- Reversible: Yes | No | Partial
--
-- Dependencies: <List tables/features that must exist before this runs, or None>
-- Data Migration: None | Inline | Separate script (see scripts/)
--
-- Rollback:
--   <SQL commands to reverse this migration>
--   DROP TABLE IF EXISTS new_table;
--   ALTER TABLE existing_table DROP COLUMN new_column;
--
-- =============================================================================

-- Your DDL statements below (generated by drizzle-kit, do not edit):

-- CREATE TABLE "example" (
--   "id" text PRIMARY KEY,
--   "created_at" timestamp with time zone DEFAULT now() NOT NULL,
--   "updated_at" timestamp with time zone DEFAULT now() NOT NULL
-- );

-- CREATE INDEX "idx_example_created_at" ON "example" ("created_at");
