/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import {
  handleImageOptimization,
  DEFAULT_DEVICE_SIZES,
  DEFAULT_IMAGE_SIZES,
} from 'vinext/server/image-optimization';
import handler from 'vinext/server/app-router-entry';
import { getDb } from '../lib/db';
import { getEmail, type SendEmail } from '../lib/email';
import { getStorage } from '../lib/r2';

// Re-export Durable Object classes so wrangler can discover them
export { SignalingRoom } from './signaling-room';

interface Env {
  ASSETS: Fetcher;
  HYPERDRIVE: { connectionString: string };
  POSTGRES_URL?: string; // local dev only: wrangler secret binding from .env.local
  R2_BUCKET?: {
    put(
      key: string,
      value:
        | ArrayBuffer
        | ArrayBufferView
        | ReadableStream
        | string
        | null
        | Blob,
      options?: { httpMetadata?: { contentType?: string } }
    ): Promise<unknown>;
    delete(keys: string | string[]): Promise<void>;
  };
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: {
          format: string;
          quality: number;
        }): Promise<{ response(): Response }>;
      };
    };
  };
  EMAIL?: SendEmail;
  SIGNALING_ROOM: DurableObjectNamespace;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Prime the db and R2 caches with CF bindings before any application code runs.
    // All subsequent getDb() / getStorage() calls return the cached instances.
    getDb(env);
    getEmail(env);
    getStorage(env);
    const url = new URL(request.url);

    // WebSocket signaling for WebRTC — route /ws/signaling/:roomId to Durable Object
    if (url.pathname.startsWith('/ws/signaling/')) {
      const roomId = url.pathname.split('/')[3];
      if (!roomId) {
        return new Response('Room ID required', { status: 400 });
      }
      const id = env.SIGNALING_ROOM.idFromName(roomId);
      const stub = env.SIGNALING_ROOM.get(id);
      return stub.fetch(request);
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === '/_vinext/image') {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(
        request,
        {
          fetchAsset: (path) =>
            env.ASSETS.fetch(new Request(new URL(path, request.url))),
          transformImage: async (body, { width, format, quality }) => {
            const result = await env.IMAGES.input(body)
              .transform(width > 0 ? { width } : {})
              .output({ format, quality });
            return result.response();
          },
        },
        allowedWidths
      );
    }

    // Delegate everything else to vinext
    return handler.fetch(request);
  },
};
